DROP POLICY IF EXISTS "Admins manage profiles" ON public.profiles;
DROP POLICY IF EXISTS "Users update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can read own roles" ON public.user_roles;
DROP POLICY IF EXISTS "Admins manage roles" ON public.user_roles;
DROP POLICY IF EXISTS "Admins manage signals" ON public.signals;
DROP POLICY IF EXISTS "Users read own votes" ON public.votes;
DROP POLICY IF EXISTS "Users update own votes" ON public.votes;
DROP POLICY IF EXISTS "Admins manage votes" ON public.votes;
DROP POLICY IF EXISTS "Users update own vote notes" ON public.vote_notes;
DROP POLICY IF EXISTS "Moderators manage vote notes" ON public.vote_notes;
DROP POLICY IF EXISTS "Users update own comments" ON public.comments;
DROP POLICY IF EXISTS "Moderators manage comments" ON public.comments;
DROP POLICY IF EXISTS "Users delete own likes" ON public.likes;
DROP POLICY IF EXISTS "Users read own reports" ON public.reports;
DROP POLICY IF EXISTS "Moderators manage reports" ON public.reports;
DROP POLICY IF EXISTS "Admins manage HOTD" ON public.hotd;
DROP POLICY IF EXISTS "Admins read analytics" ON public.analytics_events;
DROP POLICY IF EXISTS "Users update own avatars" ON storage.objects;
DROP POLICY IF EXISTS "Users delete own avatars" ON storage.objects;

CREATE POLICY "Users update own profile" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins manage profiles" ON public.profiles FOR ALL TO authenticated USING (private.has_role(auth.uid(), 'admin')) WITH CHECK (private.has_role(auth.uid(), 'admin'));
CREATE POLICY "Users can read own roles" ON public.user_roles FOR SELECT TO authenticated USING (auth.uid() = user_id OR private.has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins manage roles" ON public.user_roles FOR ALL TO authenticated USING (private.has_role(auth.uid(), 'admin')) WITH CHECK (private.has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins manage signals" ON public.signals FOR ALL TO authenticated USING (private.has_role(auth.uid(), 'admin') OR private.has_role(auth.uid(), 'moderator')) WITH CHECK (private.has_role(auth.uid(), 'admin') OR private.has_role(auth.uid(), 'moderator'));
CREATE POLICY "Users read own votes" ON public.votes FOR SELECT TO authenticated USING (auth.uid() = user_id OR private.has_role(auth.uid(), 'admin') OR private.has_role(auth.uid(), 'moderator'));
CREATE POLICY "Users update own votes" ON public.votes FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins manage votes" ON public.votes FOR ALL TO authenticated USING (private.has_role(auth.uid(), 'admin')) WITH CHECK (private.has_role(auth.uid(), 'admin'));
CREATE POLICY "Users update own vote notes" ON public.vote_notes FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Moderators manage vote notes" ON public.vote_notes FOR ALL TO authenticated USING (private.has_role(auth.uid(), 'admin') OR private.has_role(auth.uid(), 'moderator')) WITH CHECK (private.has_role(auth.uid(), 'admin') OR private.has_role(auth.uid(), 'moderator'));
CREATE POLICY "Users update own comments" ON public.comments FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Moderators manage comments" ON public.comments FOR ALL TO authenticated USING (private.has_role(auth.uid(), 'admin') OR private.has_role(auth.uid(), 'moderator')) WITH CHECK (private.has_role(auth.uid(), 'admin') OR private.has_role(auth.uid(), 'moderator'));
CREATE POLICY "Users delete own likes" ON public.likes FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users read own reports" ON public.reports FOR SELECT TO authenticated USING (auth.uid() = reporter_id OR private.has_role(auth.uid(), 'admin') OR private.has_role(auth.uid(), 'moderator'));
CREATE POLICY "Moderators manage reports" ON public.reports FOR ALL TO authenticated USING (private.has_role(auth.uid(), 'admin') OR private.has_role(auth.uid(), 'moderator')) WITH CHECK (private.has_role(auth.uid(), 'admin') OR private.has_role(auth.uid(), 'moderator'));
CREATE POLICY "Admins manage HOTD" ON public.hotd FOR ALL TO authenticated USING (private.has_role(auth.uid(), 'admin') OR private.has_role(auth.uid(), 'moderator')) WITH CHECK (private.has_role(auth.uid(), 'admin') OR private.has_role(auth.uid(), 'moderator'));
CREATE POLICY "Admins read analytics" ON public.analytics_events FOR SELECT TO authenticated USING (private.has_role(auth.uid(), 'admin'));
CREATE POLICY "Users update own avatars" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]) WITH CHECK (bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]);
CREATE POLICY "Users delete own avatars" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]);